Web/Shard/Controllers/DataLanesController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using Shard.Data;
using Shard.Models;

namespace Shard.Controllers
{
    public class DataLanesController : Controller
    {
        private readonly ShardContext _context;

        public DataLanesController(ShardContext context)
        {
            _context = context;
        }


        public IActionResult GetLanes()
        { 

            return View(new LaneViewModel() { 
                Lanes = _context.Set<DataLane>().ToList(),
                Slivers = _context.Set<DataSliver>()
                    .Where(w => w.LaneId != null)
                    .ToList(),
            });
        }
        
        // GET: DataLanes
        public async Task<IActionResult> Index()
        {
            return View(await _context.DataLane.ToListAsync());
        }

        // GET: DataLanes/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var dataLane = await _context.DataLane
                .FirstOrDefaultAsync(m => m.Id == id);
            if (dataLane == null)
            {
                return NotFound();
            }

            return View(dataLane);
        }

        // GET: DataLanes/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: DataLanes/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Id,Title,LaneOrder")] DataLane dataLane)
        {
            if (ModelState.IsValid)
            {
                _context.Add(dataLane);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(dataLane);
        }

        // GET: DataLanes/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var dataLane = await _context.DataLane.FindAsync(id);
            if (dataLane == null)
            {
                return NotFound();
            }
            return View(dataLane);
        }

        // POST: DataLanes/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("Id,Title,LaneOrder")] DataLane dataLane)
        {
            if (id != dataLane.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(dataLane);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!DataLaneExists(dataLane.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(dataLane);
        }

        // GET: DataLanes/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            var dataLane = await _context.DataLane.FindAsync(id);
            if (dataLane != null)
            {
                _context.DataLane.Remove(dataLane);
            }

            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool DataLaneExists(int id)
        {
            return _context.DataLane.Any(e => e.Id == id);
        }
    }
}

Web/Shard/Controllers/DataSliversController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Html;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using Shard.Data;
using Shard.Models;

namespace Shard.Controllers
{
    public class DataSliversController : Controller
    {
        private readonly ShardContext _context;

        public DataSliversController(ShardContext context)
        {
            _context = context;
        }

        // GET: DataSlivers
        public async Task<IActionResult> Index()
        {
            return View(await _context.DataSliver.ToListAsync());
        }

        // GET: DataSlivers/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var dataSliver = await _context.DataSliver
                .FirstOrDefaultAsync(m => m.Id == id);
            if (dataSliver == null)
            {
                return NotFound();
            }

            return View(dataSliver);
        }

        // GET: DataSlivers/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: DataSlivers/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Id,Title,Description,ParentId,LaneId")] DataSliver dataSliver)
        {
            if (ModelState.IsValid)
            {
                _context.Add(dataSliver);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(dataSliver);
        }

        // GET: DataSlivers/Edit/5
        public async Task<IActionResult> Edit(int? id, int? CurrentId)
        {
            if (id == null)
            {
                return NotFound();
            }

            var dataSliver = await _context.DataSliver.FindAsync(id);
            if (dataSliver == null)
            {
                return NotFound();
            }
            ViewBag.CurrentId = CurrentId;

            return View(dataSliver);
        }

        // POST: DataSlivers/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, int? CurrentId, [Bind("Id,Title,Description,ParentId,LaneId")] DataSliver dataSliver)
        {
            if (id != dataSliver.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    var dataBaseSliver = await _context.DataSliver.FindAsync(id);
                    //_context.Update(dataSliver);
                    dataBaseSliver.Title = dataSliver.Title;
                    dataBaseSliver.Description = dataSliver.Description;
                    dataBaseSliver.ParentId = dataSliver.ParentId;
                    dataBaseSliver.LaneId = dataSliver.LaneId;

                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!DataSliverExists(dataSliver.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction("GetShard", "Home", new { Id = CurrentId });
            }
            return View(dataSliver);
        }

        // GET: DataSlivers/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            var dataSliver = await _context.DataSliver.FindAsync(id);
            if (dataSliver != null)
            {
                _context.DataSliver.Remove(dataSliver);
            }

            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool DataSliverExists(int id)
        {
            return _context.DataSliver.Any(e => e.Id == id);
        }

        public IActionResult Titles()
        {
            ViewData["Title"] = "Titles";

            var retVal = new StringBuilder("<tt>");

            AddRef(_context.Set<DataSliver>().Find(1));

            retVal.AppendLine("</tt>");

            return View("Plain", new HtmlString(retVal.ToString()));

            void AddRef(DataSliver node)
            {
                retVal.AppendLine("<p>" + node.Title + "</p>");

                node.GetChildren(_context)
                    .ForEach(f => AddRef(f));
            }
        }

        public IActionResult Descriptions()
        {
            ViewData["Title"] = "Descriptions";

            var retVal = new StringBuilder();

            AddRef(_context.Set<DataSliver>().Find(1));

            return View("Plain", new HtmlString(retVal.ToString()));

            void AddRef(DataSliver node)
            {
                if (node.Description != null && node.Description.Contains("<"))
                {
                    retVal.AppendLine(node.Description);
                }
                else
                {
                    retVal.AppendLine("<p>"+node.Description+"</p>");
                }
                node.GetChildren(_context)
                    .ForEach(f => AddRef(f));
            }
        }

        public IActionResult Both()
        {
            ViewData["Title"] = "Both";

            var retVal = new StringBuilder();

            AddRef(_context.Set<DataSliver>().Find(1));

            return View("Plain", new HtmlString(retVal.ToString()));

            void AddRef(DataSliver node)
            {
                retVal.AppendLine("<h4>"+node.Title+"</h4>");
                if (node.Description!= null && node.Description.Contains("<"))
                {
                    retVal.AppendLine(node.Description);
                }
                else
                {
                    retVal.AppendLine("<p>" + node.Description + "</p>");
                }
                node.GetChildren(_context)
                    .ForEach(f => AddRef(f));
            }
        }
    }
}

Web/Shard/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Shard</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
    <style>
        .container {
            max-width: 95%;
        }

        .box {
            border: 1px solid #ccc7;
            margin: 0.5em 0.25em;
            padding: 1em 0.5em 0;
            background-color: #f6f6f6;
        }

        .oddbox {
            background-color: #fff;
        }

        .box, button {
            border-radius: 1em;
        }

        .actions {
            float: right;
            text-align: right;
            font-size: 10px;
        }

            .actions button {
                border: solid 1px #0003;
                background: #def;
            }

        .self {
            width: 100%;
            position: relative;
        }

        .shard {
            display: flex;
            overflow: hidden;
            flex-grow: 2;
            -webkit-flex-flow: row;
            flex-flow: row wrap;
            justify-content: flex-end;
            align-items: stretch;
            align-content: stretch;
            min-width: 14em;
            min-height: 7em;
        }

            .shard h2 {
                font-size: 1.5em;
                text-overflow: ellipsis;
                text-wrap: none;
            }

            .shard .shard {
                font-size: 0.93em;
                box-shadow: inset hsl(90, 100%, 70%) 1px -1px;
            }

                .shard .shard .shard {
                    box-shadow: inset hsl(180, 100%, 70%) 1px -1px;
                }

                    .shard .shard .shard .shard {
                        box-shadow: inset hsl(270, 100%, 70%) 1px -1px;
                    }

                        .shard .shard .shard .shard .shard {
                            box-shadow: inset hsl(45, 100%, 70%) 1px -1px;
                        }

                            .shard .shard .shard .shard .shard .shard {
                                box-shadow: inset hsl(135, 100%, 70%) 1px -1px;
                            }

                                .shard .shard .shard .shard .shard .shard .shard {
                                    box-shadow: inset hsl(-135, 100%, 70%) 1px -1px;
                                }

                                    .shard .shard .shard .shard .shard .shard .shard .shard {
                                        box-shadow: inset hsl(-45, 100%, 70%) 1px -1px;
                                    }

                                        .shard .shard .shard .shard .shard .shard .shard .shard .shard {
                                            box-shadow: inset hsl(0, 100%, 70%) 1px -1px;
                                        }

                                            .shard .shard .shard .shard .shard .shard .shard .shard .shard .shard {
                                            box-shadow: none;
                                        }
        .leaf {
            background-color: #ffe;
        }
    </style>
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Slivers</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="DataLanes" asp-action="GetLanes">Lanes</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="DataSlivers" asp-action="Titles">Titles</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="DataSlivers" asp-action="Descriptions">Descriptions</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="DataSlivers" asp-action="Both">Both</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="DataSlivers" asp-action="Index">Sliver Admin</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="DataLanes" asp-action="Index">Lane Admin</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2023 - Shard - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>